{{- if not .Values.config.ssh.existingSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- with (include "athens-proxy.secrets.ssh.annotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (include "athens-proxy.secrets.ssh.labels" . | fromYaml) }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "athens-proxy.fullname" . }}-ssh
  namespace: {{ .Release.Namespace }}
stringData:
  config: |
    {{- tpl $.Values.config.ssh.secret.config $ | nindent 4 }}
  {{- if .Values.config.ssh.secret.id_ed25519 }}
  id_ed25519: |
    {{- .Values.config.ssh.secret.id_ed25519 | nindent 4 }}
  {{- end }}
  {{- if .Values.config.ssh.secret.id_ed25519_pub }}
  id_ed25519.pub: |
    {{- .Values.config.ssh.secret.id_ed25519_pub | nindent 4 }}
  {{- end }}
  {{- if .Values.config.ssh.secret.id_rsa }}
  id_rsa: |
    {{- .Values.config.ssh.secret.id_rsa | nindent 4 }}
  {{- end }}
  {{- if .Values.config.ssh.secret.id_rsa_pub }}
  id_rsa.pub: |
    {{- .Values.config.ssh.secret.id_rsa_pub | nindent 4 }}
  {{- end }}
{{- end }}
