apiVersion: v1
kind: Secret
metadata:
  name: {{ include "athens-proxy.fullname" . }}
type: Opaque
stringData:

  {{- if not (hasKey .Values "config") -}}
  {{- $_ := set .Values "config" dict -}}
  {{- end -}}

  {{- if not (hasKey .Values.config "ATHENS_DISK_STORAGE_ROOT") -}}
  {{- $_ := set .Values.config "ATHENS_DISK_STORAGE_ROOT" "/var/lib/athens" -}}
  {{- end -}}

  {{- if not (hasKey .Values.config "ATHENS_STORAGE_TYPE") -}}
  {{- $_ := set .Values.config "ATHENS_STORAGE_TYPE" "disk" -}}
  {{- end -}}

  {{/* SETUP CONFIG */}}
  {{ range $key, $value := .Values.config }}
  {{ upper $key}}: {{ quote $value }}
  {{ end }}