apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "athens-proxy.labels" . | nindent 4 }}
  name: {{ include "athens-proxy.fullname" . }}